//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SandwichSwap
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sandwich_Topping
    {
        public int Id { get; set; }
        public int SandwichId { get; set; }
        public int ToppingId { get; set; }
    
        public virtual Sandwich Sandwich { get; set; }
        public virtual Topping Topping { get; set; }
    }
}
