//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SandwichSwap
{
    using System;
    using System.Collections.Generic;
    
    public partial class Topping
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Topping()
        {
            this.Sandwiches = new HashSet<Sandwich>();
        }
    
        public int Id { get; set; }
        public Nullable<float> price { get; set; }
        public string imageURL { get; set; }
        public string name { get; set; }
        public int category { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sandwich> Sandwiches { get; set; }
    }
}
